export enum warning {
  coverUrl = 'Hero photo not set.',
  noBodyAlt = 'Missing photo alt text: have keywords in alt text for SEO.',
  shortTitle = 'Title too short (recommended min 50 chars).',
  longTitle = 'Title too long (recommended max 60 chars).',
  lognSlug = 'Slug too long (recommended max 255 chars).',
  slug = 'Default permalink: customise permalink with keywords for SEO.',
  slugUnigue = 'Slug must be unique',
  noSearchTitle = 'Default search title: customise search title with keywords for SEO.',
  noSocialTitle = 'Default social title: customise social title with keywords for SEO.',
  shortSearchTitle = 'Search title too short (under 50 chars).',
  longSearchTitle = 'Search title too long (recommended 60 chars).',
  searchDescription = 'Search description too short (under 50 chars).',
  shortSocialTitle = 'Social title too short (under 50 chars).',
  longSocialTitle = 'Social title too short long (recommended 60 chars).',
  socialDescription = 'Social description too short (under 50 chars).',
  noMedia = 'Article body lacks images or rich media. Add rich media for better engagement.',
  TWText = 'Text too long (max 255 chars).',
  none = '',
}
