// Generated by CodiumAI

import { withHttps } from 'ufo'
import { setActivePinia } from 'pinia'
import { useSiteURL } from '../site-url'
import { setupTestPinia } from '~/test-helpers'
import { useSiteStore } from '~/stores/site'
import type { Site } from '~/graphql-operations'

beforeEach(() => {
  setActivePinia(setupTestPinia())
})

describe('useSiteURL', () => {
  // Returns the correct site URL when no third-party integrations are enabled
  it('should return the correct site URL when no third-party integrations are enabled', () => {
    // Mock the necessary dependencies
    const siteStore = useSiteStore()

    siteStore.site = {
      customer_site_domain: 'example.com',
    } as unknown as Site

    // Mock the computed properties
    const domain = computed(() => siteStore.site?.customer_site_domain ?? '')
    const siteURL = computed(() => withHttps(domain.value))

    // Invoke the function
    const { siteURL: result } = useSiteURL()

    // Assert the result
    expect(result.value).toBe(siteURL.value)
  })
})
