compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: "${GITHUB_TOKEN-}"
  //registry.tiptap.dev:
    npmAuthToken: Cwn1+I9xSYqqdUPB0icPP1Vm8r6dMVvTlZ7M8Ov71pg=

npmScopes:
  storipress:
    npmRegistryServer: "https://npm.pkg.github.com"
  tiptap-pro:
    npmRegistryServer: "https://registry.tiptap.dev/"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
