/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LeftHandNav: typeof import('./src/components/ui/LeftHandNav/LeftHandNav.vue')['default']
    LeftHandNavBody: typeof import('./src/components/ui/LeftHandNav/LeftHandNavBody.vue')['default']
    LeftHandNavFooter: typeof import('./src/components/ui/LeftHandNav/LeftHandNavFooter.vue')['default']
    LeftHandNavHeader: typeof import('./src/components/ui/LeftHandNav/LeftHandNavHeader.vue')['default']
    LeftHandNavItem: typeof import('./src/components/ui/LeftHandNav/LeftHandNavItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./src/components/ui/Section/Section.vue')['default']
    SectionContent: typeof import('./src/components/ui/Section/SectionContent.vue')['default']
    SectionContentBlock: typeof import('./src/components/ui/Section/SectionContentBlock.vue')['default']
  }
}
