export default [
  { text: '(GMT -11:00) Midway Island, Samoa', value: 'Pacific/Pago_Pago', utc: '-11:00' },
  { text: '(GMT -10:00) Hawaii', value: 'Pacific/Honolulu', utc: '-10:00' },
  { text: '(GMT -9:00) Alaska', value: 'America/Anchorage', utc: '-09:00' },
  { text: '(GMT -8:00) Chihuahua, La Paz, Mazatlan', value: 'America/Tijuana', utc: '-08:00' },
  {
    text: '(GMT -8:00) Pacific Time (US & Canada); Tijuana',
    value: 'America/Los_Angeles',
    utc: '-08:00',
  },
  { text: '(GMT -7:00) Arizona', value: 'America/Phoenix', utc: '-07:00' },
  { text: '(GMT -7:00) Mountain Time (US & Canada)', value: 'America/Denver', utc: '-07:00' },
  { text: '(GMT -6:00) Central America', value: 'America/Costa_Rica', utc: '-06:00' },
  { text: '(GMT -6:00) Central Time (US & Canada)', value: 'America/Chicago', utc: '-06:00' },
  {
    text: '(GMT -6:00) Guadalajara, Mexico City, Monterrey',
    value: 'America/Mexico_City',
    utc: '-06:00',
  },
  { text: '(GMT -6:00) Saskatchewan', value: 'America/Regina', utc: '-06:00' },
  { text: '(GMT -5:00) Bogota, Lima, Quito', value: 'America/Bogota', utc: '-05:00' },
  { text: '(GMT -5:00) Eastern Time (US & Canada)', value: 'America/New_York', utc: '-05:00' },
  { text: '(GMT -5:00) Indiana (East)', value: 'America/Guayaquil', utc: '-05:00' },
  { text: '(GMT -4:00) Caracas, La Paz', value: 'America/Caracas', utc: '-04:00' },
  {
    text: '(GMT -4:00) Atlantic Time (Canada); Brasilia, Greenland',
    value: 'America/Halifax',
    utc: '-04:00',
  },
  { text: '(GMT -4:00) Santiago', value: 'America/Santiago', utc: '-04:00' },
  { text: '(GMT -3:30) Newfoundland', value: 'America/St_Johns', utc: '-03:30' },
  {
    text: '(GMT -3:00) Buenos Aires, Georgetown',
    value: 'America/Argentina/Buenos_Aires',
    utc: '-03:00',
  },
  { text: '(GMT -2:00) Fernando de Noronha', value: 'America/Noronha', utc: '-02:00' },
  { text: '(GMT -1:00) Azores', value: 'Atlantic/Azores', utc: '-01:00' },
  { text: '(GMT -1:00) Cape Verde Is.', value: 'Atlantic/Cape_Verde', utc: '-01:00' },
  { text: '(GMT) UTC', value: 'UTC' },
  { text: '(GMT +0:00) Casablanca, Monrovia', value: 'Africa/Casablanca', utc: '+00:00' },
  { text: '(GMT +0:00) Dublin, Edinburgh, London', value: 'Europe/Dublin', utc: '+00:00' },
  {
    text: '(GMT +1:00) Amsterdam, Berlin, Rome, Stockholm, Vienna',
    value: 'Europe/Amsterdam',
    utc: '+01:00',
  },
  {
    text: '(GMT +1:00) Belgrade, Bratislava, Budapest, Prague',
    value: 'Europe/Prague',
    utc: '+01:00',
  },
  {
    text: '(GMT +1:00) Brussels, Copenhagen, Madrid, Paris',
    value: 'Europe/Paris',
    utc: '+01:00',
  },
  {
    text: '(GMT +1:00) Sarajevo, Skopje, Warsaw, Zagreb',
    value: 'Europe/Warsaw',
    utc: '+01:00',
  },
  { text: '(GMT +1:00) West Central Africa', value: 'Africa/Lagos', utc: '+01:00' },
  {
    text: '(GMT +2:00) Athens, Beirut, Bucharest, Istanbul',
    value: 'Europe/Istanbul',
    utc: '+02:00',
  },
  { text: '(GMT +2:00) Cairo, Egypt', value: 'Africa/Cairo', utc: '+02:00' },
  { text: '(GMT +2:00) Harare', value: 'Africa/Maputo', utc: '+02:00' },
  {
    text: '(GMT +2:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius',
    value: 'Europe/Kyiv',
    utc: '+02:00',
  },
  { text: '(GMT +2:00) Jerusalem', value: 'Asia/Jerusalem', utc: '+02:00' },
  { text: '(GMT +2:00) Pretoria', value: 'Africa/Johannesburg', utc: '+02:00' },
  { text: '(GMT +3:00) Baghdad', value: 'Asia/Baghdad', utc: '+03:00' },
  { text: '(GMT +3:00) Kuwait, Nairobi, Riyadh', value: 'Asia/Riyadh', utc: '+03:00' },
  {
    text: '(GMT +3:00) Moscow, St. Petersburg, Volgograd',
    value: 'Europe/Moscow',
    utc: '+03:00',
  },
  { text: '(GMT +3:30) Tehran', value: 'Asia/Tehran', utc: '+03:00' },
  { text: '(GMT +4:00) Abu Dhabi, Muscat', value: 'Asia/Dubai', utc: '+04:00' },
  { text: '(GMT +4:00) Baku, Tbilisi, Yerevan', value: 'Asia/Baku', utc: '+04:00' },
  { text: '(GMT +4:30) Kabul', value: 'Asia/Kabul', utc: '+04:30' },
  { text: '(GMT +5:00) Islamabad, Karachi, Tashkent', value: 'Asia/Karachi', utc: '+05:00' },
  { text: '(GMT +5:00) Yekaterinburg', value: 'Asia/Yekaterinburg', utc: '+05:00' },
  {
    text: '(GMT +5:30) Chennai, Calcutta, Mumbai, New Delhi',
    value: 'Asia/Kolkata',
    utc: '+05:30',
  },
  { text: '(GMT +5:45) Katmandu', value: 'Asia/Kathmandu', utc: '+05:45' },
  { text: '(GMT +6:00) Almaty, Novosibirsk', value: 'Asia/Almaty', utc: '+06:00' },
  {
    text: '(GMT +6:00) Astana, Dhaka, Sri Jayawardenepura',
    value: 'Asia/Dhaka',
    utc: '+06:00',
  },
  { text: '(GMT +6:30) Rangoon', value: 'Asia/Rangoon', utc: '+06:30' },
  { text: '(GMT +7:00) Bangkok, Hanoi, Jakarta', value: 'Asia/Bangkok', utc: '+07:00' },
  { text: '(GMT +7:00) Krasnoyarsk', value: 'Asia/Krasnoyarsk', utc: '+07:00' },
  {
    text: '(GMT +8:00) Beijing, Chongqing, Hong Kong, Urumqi',
    value: 'Asia/Hong_Kong',
    utc: '+08:00',
  },
  { text: '(GMT +8:00) Irkutsk, Ulaan Bataar', value: 'Asia/Irkutsk', utc: '+08:00' },
  {
    text: '(GMT +8:00) Kuala Lumpur, Perth, Singapore, Taipei',
    value: 'Asia/Singapore',
    utc: '+08:00',
  },
  { text: '(GMT +9:00) Osaka, Sapporo, Tokyo', value: 'Asia/Tokyo', utc: '+09:00' },
  { text: '(GMT +9:00) Seoul', value: 'Asia/Seoul', utc: '+09:00' },
  { text: '(GMT +9:00) Yakutsk', value: 'Asia/Yakutsk', utc: '+09:00' },
  { text: '(GMT +9:30) Adelaide', value: 'Australia/Adelaide', utc: '+09:30' },
  { text: '(GMT +9:30) Darwin', value: 'Australia/Darwin', utc: '+09:30' },
  {
    text: '(GMT +10:00) Brisbane, Guam, Port Moresby',
    value: 'Australia/Brisbane',
    utc: '+10:00',
  },
  {
    text: '(GMT +10:00) Canberra, Hobart, Melbourne, Sydney, Vladivostok',
    value: 'Australia/Sydney',
    utc: '+10:00',
  },
  {
    text: '(GMT +11:00) Magadan, Soloman Is., New Caledonia',
    value: 'Asia/Magadan',
    utc: '+11:00',
  },
  { text: '(GMT +12:00) Auckland, Wellington', value: 'Pacific/Auckland', utc: '+12:00' },
  { text: '(GMT +12:00) Fiji, Kamchatka, Marshall Is.', value: 'Pacific/Fiji', utc: '+12:00' },
  {
    text: '(GMT +12:00) International Date Line West',
    value: 'Pacific/Kwajalein',
    utc: '+12:00',
  },
  {
    text: '(GMT +13:00) New Zealand time',
    value: 'Pacific/Auckland',
    utc: '+13:00',
  },
]
