npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: '${GITHUB_TOKEN-}'

npmScopes:
  storipress:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmPublishRegistry: 'https://npm.pkg.github.com'
