query GetUser($id: ID, $slug: String) {
  user(id: $id, slug: $slug) {
    id
    slug
    email
    first_name
    last_name
    full_name
    avatar
    location
    bio
    website
    socials
    created_at
    updated_at
    desks {
      id
      name
      slug
      seo
      order
    }
  }
}
