query SubscriberStats($id: ID!) {
  subscriber(id: $id) {
    id
    email
    bounced
    first_name
    last_name
    full_name
    avatar
    newsletter
    subscribed
    subscription_type
    first_paid_at
    subscribed_at
    renew_on
    canceled_at
    expire_on
    signed_up_source
    paid_up_source
    revenue
    activity
    active_days_last_30
    comments_total
    comments_last_7
    comments_last_30
    shares_total
    shares_last_7
    shares_last_30
    email_receives
    email_opens_total
    email_opens_last_7
    email_opens_last_30
    unique_email_opens_total
    unique_email_opens_last_7
    unique_email_opens_last_30
    email_link_clicks_total
    email_link_clicks_last_7
    email_link_clicks_last_30
    unique_email_link_clicks_total
    unique_email_link_clicks_last_7
    unique_email_link_clicks_last_30
    article_views_total
    article_views_last_7
    article_views_last_30
    unique_article_views_total
    unique_article_views_last_7
    unique_article_views_last_30
    verified
    created_at
  }
}
