on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-22.04
    outputs:
      pr_number: ${{ steps.release.outputs.pr.number }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: manager-next
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"style","section":"Styles","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"refactor","section":"Refactors","hidden":false},
              {"type":"revert","section":"Reverts","hidden":false}
            ]
      - name: Actions Ecosystem Remove Labels
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        if: ${{ steps.release.outputs.pr }}
        with:
          labels: release:clear
          number: ${{ steps.release.outputs.pr.number }}
      - uses: actions/checkout@v4
      - name: create release branches
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git branch release/${{ steps.release.outputs.tag_name }}
          git push origin release/${{ steps.release.outputs.tag_name }}
          git reset --hard release/${{ steps.release.outputs.tag_name }}
          git switch -c staging
          git reset --hard release/${{ steps.release.outputs.tag_name }}
          git push -f origin staging
          git switch -c production
          git reset --hard release/${{ steps.release.outputs.tag_name }}
          git push -f origin production
          git switch master
